# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    export VCPKG_ROOT=/usr/local/share/vcpkg
    git clone https://github.com/Microsoft/vcpkg
    cd vcpkg
    ./bootstrap-vcpkg.sh
    ./vcpkg integrate install
    ./vcpkg @../SmpDataAgent/vcpkg_ref.txt
  displayName: 'Prepare VCPKG packages'
- script: |
    echo Step 1: installing packages with apt ...
    sudo apt install -y ninja-build cmake libcurl4-openssl-dev
  displayName: 'Install required package - apt'
- script: |
    sudo cmake /home/vsts/work/1/s/  --preset linux-debug -DCMAKE_TOOLCHAIN_FILE:FILEPATH="/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake"
    sudo cmake --build /usr/local/share/SmpDataAgent/bin/linux-debug --config Release
  displayName: 'Cmake build'
- script: |
    sudo cp /usr/local/share/SmpDataAgent/bin/linux-debug/SmpDataAgent/SmpDataAgent /home/vsts/work/1/a/SmpDataAgent
  displayName: 'Copy binaries'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SmpDataAgent'
    publishLocation: 'Container'
  displayName: 'Publish Binarie'