# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    git clone https://github.com/Microsoft/vcpkg
    cd vcpkg
    ls
    ./bootstrap-vcpkg.sh
    ./vcpkg integrate install
    ./vcpkg @../SmpHttpClient/vcpkg_ref.txt
    cd ..
    ls
    cd ..
    ls
    cd ..
    ls
  displayName: 'Prepare VCPKG packages'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CMake@1
  displayName: 'CMake ..'
  inputs:
    cmakeArgs: '..'
- task: CMake@1
  displayName: 'CMake --build . --config debug'
  inputs:
    cmakeArgs: '--build . --config Debug'