# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    git clone https://github.com/Microsoft/vcpkg
    cd vcpkg
    ./bootstrap-vcpkg.sh
    ./vcpkg integrate install
    ./vcpkg @../SmpHttpClient/vcpkg_ref.txt
  displayName: 'Prepare VCPKG packages'
- script: |
    sudo apt install -y ninja-build cmake
  displayName: 'Install required package - apt'
- script: |
    cmake .. --preset linux-debug
  displayName: 'Cmake build'
- task: CMake@1
  displayName: 'CMake .. --preset linux-debug'
  inputs:
    cmakeArgs: '.. --preset linux-debug'
- task: CMake@1
  displayName: 'CMake --list-presets=all ../'
  inputs:
    cmakeArgs: '--list-presets=all ../'
- task: CMake@1
  displayName: 'CMake --preset linux-debug'
  inputs:
    cmakeArgs: '--preset linux-debug'
- task: CMake@1
  displayName: 'CMake build'
  inputs:
    cmakeArgs: '--build . --config Debug'

- task: CMake@1
  displayName: 'CMake --build  --config Debug --preset linux-debug' #-DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake'
  inputs:
    cmakeArgs: '--build  --config Debug --preset linux-debug'